---
title: "Temas Selectos en Estadística"
author: "Christian F. Badillo H."
format: 
    revealjs: 
        incremental: false
        scrollable: true
        smaller: true
        theme: night
        logo: images/Lab25_logo_2015.png
        footer: "Temas Selectos en Estadística"
        preview-links: true
        preload-iframes: true
        slide-number: true
        transition: convex
        background-transition: fade
        transition-speed: slow
        navigation-mode: linear
        touch: true
        controls: true
        embed-resources: true
        page-layout: custom
---

## Logística del Curso

* **Ponente:** Christian Francisco Badillo Hernández.
* **Correo:** [cris.badillo1408@gmail.com](mailto:cris.badillo1408@gmail.com).
* **Modalidad**: Presencial.
* **Horario**: Lunes, Martes, Jueves y Viernes de 12:00 a 14:00 hrs (24 hrs totales).
* ***Dirigido a todos los semestres.***
* El curso es autocontenido y no requiere de conocimientos previos en estadística ni en programación.

## Objetivos del Curso

* El objetivo del curso es que el alumno aprenda los principios generales en estadística inferencial y que sea capaz de aplicarlos en la resolución de problemas reales.

* El curso se enfoca en la ejemplificación de los conceptos con el uso de simulaciones computacionales (en formato de widgets) en los lenguajes de programación [`R`](https://www.r-project.org/) y [`Python`](https://es.wikipedia.org/wiki/Python).


## Temario

1. **Repaso de Estadística Descriptiva**.
    1. *Procesos generadores de datos*.
        1. Probabilidad.
        2. Distribuciones de Probabilidad.
    2. *Descripción de datos*. 
        1. Media, moda, mediana, curtosis, asimetría.
        2. Varianza, rango, desviación estándar, percentiles.
    3. *Visualizaciones básicas*.
        1. Histogramas.
        2. Boxplots.
        3. Diagramas de violín.
        4. Scatter plot.
    4. *Consideraciones y teoremas importantes*.
        1. Muestreo aleatorio.
        2. Ley de los grandes números.
        3. Teorema del límite central.

2. **Estimación en Estadística**.
    1. *Mínimos Cuadrados*.
    2. *Máxima Verosimilitud*.
    3. *Estimación Bayesiana*.

3. **Modelos Lineales Generalizados**.
    1. *Modelo lineal simple*.
        1. Modelo lineal general.
        2. Regresión Lineal.
    2. *Modelos no lineales*.
        1. Conceptos básicos.
        2. Modelo Logístico.
        3. Modelo de Poisson.

4. **Comparación de Modelos (Prueba de Hipótesis)**.
    1. *T-Student*.
    2. *ANOVA*.
    3. *Chi-cuadrada*.
    4. *Prueba de Wilcoxon-Mann-Whitney*.
    5. *Prueba de Kruskal-Wallis*.
    6. *Valores P, Factor de Bayes y Grados de Libertad*.

5. **Aplicaciones en Psicología**.
    1. *Ley Generalizada de Igualación*.
    2. *Predicción de disparos neuronales*.
    3. *Psicometría: Modelo de Rasch*.


::: footer
Pudes dezplazarte hacia abajo para ver el temario completo.
:::

## Referencias

* DeGroot, M. H., & Schervish, M. J. (2012). *Probability and statistics. Pearson*.

* Hastie, T., Tibshirani, R., & Friedman, J. (2009). *The elements of statistical learning: Data Mining, Inference, and Prediction*, Second Edition. Springer Science & Business Media.

* Maxwell, S. E., Delaney, H. D., & Kelley, K. (2018). *Designing Experiments and Analyzing Data: A Model Comparison Perspective (3rd ed.)*. New York: Routledge.

* McElreath, R. (2015). *Statistical rethinking: A Bayesian Course With Examples in R and Stan*. Chapman & Hall/CRC.

* Poldrack, R. A. (2023). *Statistical thinking: Analyzing Data in an Uncertain World*. Princeton University Press.

* Stigler, Stephen M. 2016. *The Seven Pillars of Statistical Wisdom*. Harvard University Press.

* Wheelan, C. (2014). *Naked Statistics: Stripping The Dread From The Data*. National Geographic Books.

::: footer
Pudes dezplazarte hacia abajo para ver todas las referencias.
:::

## Nota sobre las Presentaciónes

* Las presentaciones utilizan herramientas como [`reveal.js`](https://revealjs.com/), [`webR`](https://quarto-webr.thecoatlessprofessor.com/), [`Shiny`](https://shiny.posit.co/), [`Jupyter Notebook`](https://jupyter.org/), y [`Quarto`](https://quarto.org/) para generar presentaciones interactivas, dinámicas y con la posibilidad de correr código en vivo.

* Las presentaciones se encuentran en formato `HTML` y pueden ser visualizadas en cualquier navegador web moderno, además pueden ser exportadas a PDF presionando la tecla "e".